### PR TITLE
Verify contracts using Solc standard JSON input

### LINKED ISSUE #414: Contract verification fails when flattened source contains contracts with the same name
First of all, thanks a lot for this wonderful tool.

**Issue**
I've encountered an issue using the source verification task. When the project structure contains multiple contracts with the same name in different paths, the global flattened source file built by the `flatten` task and used by the `verify-contract` task does not compile, e.g.:

```bash
.
└── project
    ├── contracts
    │   ├── A.sol
    │   ├── B.sol
    │   └── C.sol
    └── imported
        └── C.sol
```
or

```bash
.
└── project
    └── contracts
        ├── A.sol
        ├── B.sol
        ├── C.sol
        └── imported
            └── C.sol
```

because two contracts `C` appear in the global flattened source.

This project setup is far from ideal and IMHO should be avoided if possible, however some projects do have this layout for good reasons, e.g. [RTokens](https://github.com/rtoken-project/rtoken-contracts) and after all the `solc` compiler handles it gracefully, if the relative inheritance trees do not contain name clashes.

_Environment_

Ubuntu 18.04
Solc 0.5.15
Buidler 1.0.2

**Proposed Solution**
Thinking about how to overcome this limitation in the `verify-contract` task, I've come up with an idea: instead of flattening the sources into one unique file, we could use the `solc` standard input JSON already produced (but not saved) by the `compile:compile` subtask.

This solves any issue coming from the flattening process itself and also guarantees that whenever `solc` compiles successfully, also the source verification will be OK.

I've tried to modify the `compile` task to save the standard input JSON and read it in the `verify-contract` task to call the Etherscan API using the standard input JSON format: it seems to work fine, also in case of multiple contracts with the same name.

I'm preparing a PR with as little changes as possible (tasks and unit tests) to implement this and I will submit it, if it sounds good.

### PR DESCRIPTION
**Pull request by canepat**
This PR introduces the contract source verification on Etherscan using the Solc standard JSON input as proposed in issue #414.

Fixes #414

**Working Assumptions**
I've made the following working assumptions:

- a new test project `contracts-nameclash-project` is added to prove the name clash using flattening
- the `verify-contract` task now uses the Solc standard JSON input (instead of the Solidity single-file provided by flattening) as code format with Etherscan API
- the `buidler-etherscan` test project is extended with contracts producing some name clash
- the Solc standard JSON input is currently saved in `config.paths.artifacts` folder
- the Solc version for the `buidler-etherscan` test project is upgraded to 0.5.15 because using version 0.5.1 I was unable to verify on Etherscan the existent `TestContract1`, just upgrading Solc makes it work

**Limitations**
Currently there are some limitations:

- the Solc standard JSON input is saved always in `config.paths.artifacts` folder, no customization is possible
- when using the Solc standard JSON input the [Etherscan API spec](https://etherscan.io/apis#contracts) requires that the `contractName` parameter is provided in the `<path_to_sol>:<contract_name>` format. Currently it is hard-coded as `contracts/${taskArgs.contractName}.sol:${taskArgs.contractName}` in `buidler-etherscan`: far from ideal but making it work for any contract would require to change the `verify-contract` task arguments, so I prefer to leave this for a next PR, if this one is accepted

I'm looking forward to hear if this PR sounds good and in case to receive any advice or suggestion for improving this solution

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey @canepat,

Thanks for making this PR. I'm sorry I couldn't review it earlier.

I'm a little confused about how this works, as my understanding is that etherscan's API only accepts flattened sources and not the standard json input.

**Comment by alcuadrado** [comment]
Ohhhh, they just reuse some param names, but support the standard json format now! This is great news! 🥳

I'll look deeper into this later, but looking really good so far.

Much appreciated!

**Comment by canepat** [comment]
I've just added the usage of `await bre.run(TASK_COMPILE_GET_COMPILER_INPUT)` removing the unnecessary custom functions for loading/saving the standard Solc JSON input.

The last commit passes in Travis CI but fails in Netlify for some reason I don't understand, if you have any clue it would be great.

**Comment by alcuadrado** [comment]
Thanks @canepat!

I cleared netlifies cache, re-run it, and not it works. 

I'll review your changes tomorrow.

File: packages/buidler-etherscan/src/index.ts [hunk 1]
```diff
@@ -46,30 +47,23 @@ task("verify-contract", "Verifies contract on etherscan")
...
       config.solc.fullVersion = await getLongVersion(config.solc.version);
 
+      const source = JSON.stringify(await run(TASK_COMPILE_GET_COMPILER_INPUT));
+
       const request = toRequest({
         apiKey: etherscan.apiKey,
         contractAddress: taskArgs.address,
         sourceCode: source,
-        contractName: taskArgs.contractName,
+        contractName: `contracts/${taskArgs.contractName}.sol:${taskArgs.contractName}`,
```
Comment (alcuadrado) [inline packages/buidler-etherscan/src/index.ts]: This line is the only problematic thing I can see, as it imposes the same names for files and contracts.

This could be fixed by doing something like

```ts
const solcInput : SolcInput = JSON.stringify(await run(TASK_COMPILE_GET_COMPILER_INPUT)); 

const filesWithContract = Object.entries(solcInput.sources).find((fileGlobalName, {content}) => hasContractDeclaration(content, taskArgs.contractName)).map((globalName) => globalName);

if (filesWithContract.length === 0) {
   // contract not found
   throw BuidlerPluginError(...);
}

if (filesWithContract.length > 1) {
   // throw error? what should be done here??
}

const contractName = `${filesWithContract[0}:${taskArgs.contractName}`;
```

Comment (canepat) [reply packages/buidler-etherscan/src/index.ts]: Yes, you're absolutely right, it's a known limitation for this PR.

My idea for handling any use case is extending the `verify-contract` task arguments to accept an optional `contractPath` argument (e.g. contracts/A.sol) to build the complete contract name as `${taskArgs.contractPath}:${taskArgs.contractName}`; when the `contractPath` is not given, the name `contracts/${taskArgs.contractName}.sol:${taskArgs.contractName}` will be used.

Another option could be changing the `contractName` argument of the `verify-contract` task to become the full contract name, specified exactly as expected by Etherscan API (e.g. contracts/A.sol:B.sol).

What do you think?

Comment (pcowgill) [reply packages/buidler-etherscan/src/index.ts]: @alcuadrado Does this issue gate merging? Thanks!

Comment (canepat) [reply packages/buidler-etherscan/src/index.ts]: @pcowgill this issue has been resolved in last commit

**Comment by pcowgill** [comment]
@alcuadrado Whenever you have time, there’s another commit here for your review. Thanks!

File: packages/buidler-etherscan/src/index.ts (hunk 1 above)
Comment (pcowgill) [reply packages/buidler-etherscan/src/index.ts]: @canepat Great, thanks. I thought so but I wanted to confirm that

**Comment by alcuadrado** [comment]
Hey @canepat and @pcowgill, we were a little busy preparing [this new release](https://github.com/nomiclabs/buidler/releases/tag/v1.2.0). Now that it's out, I'll review this soon.

Can you update it and change the base branch to `development`? Thanks!

**Comment by canepat** [comment]
I've just merged from and changed the base branch to `development`.

**Comment by pcowgill** [comment]
@tmilar @fvictorio Might either of you have a chance to review this PR this week or next? Thanks!

**Comment by alcuadrado** [comment]
Thanks for creating this PR @canepat, and thanks for your patience!
